### ISSUE TITLE
Publishing to Clojars?

### ISSUE THREAD

**Issue by danielcompton** [wagjo/tools-cljs#1]
This project doesn't seem to be on Clojars, so I can't use it for benchmark-cljs without installing locally. Are you able to publish this on clojars? Thanks.

**Comment by wagjo** [comment]
Published as version [0.1.0](https://clojars.org/com.wagjo/tools-cljs). Done the same for [wagjo/data-cljs](https://clojars.org/com.wagjo/data-cljs)
